### PR TITLE
Renamed package to reflect forked project's new maintainer.

### PR DESCRIPTION
**Pull request by CalebWC**
From the Magento docs:

> Package (also often referred to as a Namespace) is a unique name that identifies your company or organization. The intent is that each member of the world-wide Magento community will use their own Package name when creating modules in order to avoid colliding with another user's code.

### CODE REVIEW

**Comment by benmccormick** [comment]
There are references to the old paths in

```
> ack 'Segment/' -l
dist/var/connect/analytics.xml
Readme.md
```

**Comment by CalebWC** [comment]
@benmccormick: I hadn't rebuilt the dist folder. Should be fixed now (as of a5f8ba288ae8bda49e26c7639c2ee1dc93f8b3f4).

**Comment by benmccormick** [comment]
Just noticed:  

> From the Magneto docs:

magneto

**Comment by CalebWC** [comment]
All better. Sorry, McKellen/Fassbender.

**Pull request merged**
